/*
* Copyright (c) 2020 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

#include <stdio.h>
#include "bsp_api.h"
#include "rm_mcuboot_port.h"
#include "rm_mcuboot_port_cfg.h"
#include "bootutil/bootutil_log.h"
#include "flash_map_backend/flash_map_backend.h"
#include "sysflash/sysflash.h"

#if BSP_FEATURE_MRAM_IS_AVAILABLE
 #include "r_mram.h"

 #if RM_MCUBOOT_DUAL_BANK_ENABLED
  #define R_FLASH_BankSwap    R_MRAM_BankSwap
 #endif

#elif BSP_FEATURE_FLASH_HP_VERSION > 0
 #include "r_flash_hp.h"

 #if RM_MCUBOOT_DUAL_BANK_ENABLED
  #define R_FLASH_BankSwap    R_FLASH_HP_BankSwap
 #endif

#else
 #include "r_flash_lp.h"
 #include "r_flash_lp_cfg.h"

 #if RM_MCUBOOT_DUAL_BANK_ENABLED
  #define R_FLASH_BankSwap    R_FLASH_LP_BankSwap
 #endif

#endif

#if (1U == FLASH_LP_CFG_DUAL_BANK_INSTANT_SWAP)
 #define RM_MCUBOOT_BOOT_WITHOUT_RESET    (FLASH_LP_CFG_DUAL_BANK_INSTANT_SWAP)

 #ifndef RM_MCUBOOT_PORT_CFG_MCUBOOT_SIZE

/*
 * NOTE:
 * BSP_PARTITION_FLASH_BL_CPU0_SIZE is generated by the Solution Project.
 * During standalone bootloader build, this macro may not be defined yet.
 * Set a temporary value (0U) to avoid build errors.
 * The correct value will be applied when the Solution Project is built.
 */
  #ifndef BSP_PARTITION_FLASH_BL_CPU0_SIZE
   #define RM_MCUBOOT_PORT_CFG_MCUBOOT_SIZE    (0U)
  #else
   #define RM_MCUBOOT_PORT_CFG_MCUBOOT_SIZE    (BSP_PARTITION_FLASH_BL_CPU0_SIZE)
  #endif
 #endif

#endif

#if defined(__GNUC__) && !defined(__ARMCC_VERSION) && !defined(__clang_analyzer__)
 #define RM_MCUBOOT_PORT_NAKED_FUNCTION    __attribute__((naked, no_instrument_function, \
                                                          no_profile_instrument_function))
#else
 #define RM_MCUBOOT_PORT_NAKED_FUNCTION    BSP_ATTRIBUTE_STACKLESS
#endif

#if RM_MCUBOOT_DUAL_BANK_ENABLED
extern void * const gp_mcuboot_flash_ctrl;
#endif

#define RM_MCUBOOT_PORT_SW_RESET      (0xA501)
#define RM_MCUBOOT_RESET_WAIT_TIME    (10)

static void start_app(void * pc);

#if ((0 == RM_MCUBOOT_BOOT_WITHOUT_RESET) && (1 == RM_MCUBOOT_DUAL_BANK_ENABLED))
static void rm_mcuboot_port_reset();

#endif

/* Defines function pointers to be used with vector table. */
typedef void (* vec_ptr_t)(void);

/* This function jumps to the application image. */
static void start_app (void * pc)
{
    ((void (*)(void))pc)();
}

#if ((0 == RM_MCUBOOT_BOOT_WITHOUT_RESET) && (1 == RM_MCUBOOT_DUAL_BANK_ENABLED))

/* Function for issuing a reset */
static void rm_mcuboot_port_reset (void) {
    R_BSP_RegisterProtectDisable(BSP_REG_PROTECT_OM_LPC_BATT_SWR);
    R_SYSTEM->SWRR = RM_MCUBOOT_PORT_SW_RESET;
    R_BSP_RegisterProtectEnable(BSP_REG_PROTECT_OM_LPC_BATT_SWR);

    /* Checking the elapsed time since reset */
    R_BSP_SoftwareDelay(RM_MCUBOOT_RESET_WAIT_TIME, BSP_DELAY_UNITS_MILLISECONDS);

    assert(0);
}

#endif

/*******************************************************************************************************************//**
 * Cleans up resources used by bootloader port and branches to application image.
 **********************************************************************************************************************/
void RM_MCUBOOT_PORT_BootApp (struct boot_rsp * rsp) {
    BOOT_LOG_DBG("Starting Application Image\n");
    BOOT_LOG_DBG("Image Offset: 0x%x\n", (int) rsp->br_image_off);

#if !defined(MCUBOOT_DIRECT_XIP_MMF)

    /* The vector table is located after the header. Only running from internal flash is supported now. */
    uint32_t vector_table = rsp->br_image_off + rsp->br_hdr->ih_hdr_size;
#else

    /* The vector table is located at start address of MMF region when support MMF on Direct-XIP mode. */
    uint32_t vector_table = MCUBOOT_MMF_START_ADDR;

    R_BSP_MemoryMirrorAddrSet(rsp->br_image_off + rsp->br_hdr->ih_hdr_size);
#endif

#if RM_MCUBOOT_DUAL_BANK_ENABLED
 #if BSP_FEATURE_RSIP_RSIP_E51A_SUPPORTED
    if (vector_table & (BSP_FEATURE_FLASH_HP_CF_DUAL_BANK_START - BSP_FEATURE_FLASH_CODE_FLASH_START))
 #else
    if (vector_table & (BSP_FEATURE_FLASH_HP_CF_DUAL_BANK_START | BSP_FEATURE_FLASH_LP_CF_DUAL_BANK_START))
 #endif
    {
        R_FLASH_BankSwap(gp_mcuboot_flash_ctrl);

 #if RM_MCUBOOT_BOOT_WITHOUT_RESET

        /* If booting new image without reset, it is necessary to set the vector_table address to flash area 0. */
        vector_table =
            (uint32_t) (FLASH_AREA_MCUBOOT_OFFSET + RM_MCUBOOT_PORT_CFG_MCUBOOT_SIZE + rsp->br_hdr->ih_hdr_size);
 #else

        /* Reset the MCU to swap to the other bank */
        rm_mcuboot_port_reset();
 #endif
    }
#endif

    /* Get the entry point from the start of the image */
    uint32_t * app_pc;
    app_pc = (uint32_t *) (uintptr_t) (vector_table);

    /* Clean up internal flash driver. */
    rm_mcuboot_cleanup();

    BOOT_LOG_DBG("Vector Table: 0x%x. PC=0x%x\n", (unsigned int) vector_table, (unsigned int) app_pc);

    /* Set the applications vector table. */
    vector_table += sizeof(uint32_t);
    __SET_EXTB((vec_ptr_t) (uintptr_t) vector_table);

    /* Set SP and branch to PC. */
    start_app((void *) (uintptr_t) *app_pc);
}

#if defined(__ARMCC_VERSION)           /* AC6 compiler */

 #if defined MCUBOOT_SIGN_EC256 && !defined MCUBOOT_USE_MBED_TLS

/* This function is only used by MCUboot for RSA keys with mbedtls.
 * When it's not used, this function should be compiled out, but AC6 has a known issue where unused functions are not compiled out
 * so this function is created as a placeholder to get rid of the linker error. */
int mbedtls_mpi_read_binary (void * X, const unsigned char * buf, size_t buflen)
{
    FSP_PARAMETER_NOT_USED(X);
    FSP_PARAMETER_NOT_USED(buf);
    FSP_PARAMETER_NOT_USED(buflen);

    return 0;
}

 #endif
#endif
