/*
* Copyright (c) 2020 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

/*******************************************************************************************************************//**
 * @addtogroup PCIF
 * @{
 **********************************************************************************************************************/

#ifndef R_PCIF_H
#define R_PCIF_H

/***********************************************************************************************************************
 * Includes
 **********************************************************************************************************************/
#include "bsp_api.h"
#include "r_pcif_api.h"

/* Common macro for FSP header files. There is also a corresponding FSP_FOOTER macro at the end of this file. */
FSP_HEADER

/***********************************************************************************************************************
 * Macro definitions
 **********************************************************************************************************************/

/** Maximum incremental mode resolution ratio setting (INCRSL[5:0]). */
#define PCIF_INC_RESOLUTION_RATIO_SETTING_MAX                 (0x3FU)

/** Z phase generation sources that cannot be enabled together. */
#define PCIF_INC_Z_PHASE_GEN_COUNTER_INPUT_PROHIBITED_MASK    (PCIF_INC_Z_PHASE_GEN_COUNTER | \
                                                               PCIF_INC_Z_PHASE_GEN_INPUT)

/** Position clear source prohibited when counter-based Z phase generation is enabled. */
#define PCIF_INC_COUNTER_CLEAR_Z_GEN_PROHIBITED_MASK          (PCIF_INC_COUNTER_CLEAR_INPUT)

/***********************************************************************************************************************
 * Typedef definitions
 **********************************************************************************************************************/

/** Error detection enable setting. */
typedef enum e_pcif_error_detection_enable
{
    PCIF_PHC_ERROR_DETECTION_DISABLE = 0U, ///< error detection disabled
    PCIF_PHC_ERROR_DETECTION_ENABLE  = 1U, ///< error detection enabled
} pcif_phc_error_detection_enable_t;

/** Z phase width config */
typedef enum e_pcif_z_phase_width
{
    PCIF_PHC_Z_WIDTH_DISABLE = 0U,     ///< Z Width = 0, output Z phase disabled
    PCIF_PHC_Z_WIDTH_1       = 1U,     ///< Z Width = 1
    PCIF_PHC_Z_WIDTH_2       = 2U,     ///< Z Width = 2
    PCIF_PHC_Z_WIDTH_3       = 3U,     ///< Z Width = 3
    PCIF_PHC_Z_WIDTH_4       = 4U,     ///< Z Width = 4
} pcif_phc_z_phase_width_t;

/** Phase Counting mode Z phase sync */
typedef enum e_pcif_z_phase_sync
{
    PCIF_PHC_SYNC_PHASE_A = 0U,        ///< Z phase sync with A PHASE
    PCIF_PHC_SYNC_PHASE_B = 1U,        ///< Z phase sync with B PHASE
} pcif_phc_z_phase_sync_t;

/** Phase Counting mode carrier cycle event difference adjustment mode */
typedef enum e_pcif_carrier_period_mode
{
    PCIF_PHC_CARRIER_PERIOD_MODE_EVENT_BASED    = 0U, ///< Carrier period is generated by ELC
    PCIF_PHC_CARRIER_PERIOD_MODE_REGISTER_BASED = 1U, ///< Carrier period is generated by internal counter
} pcif_phc_carrier_period_mode_t;

/** Phase Counting mode automatic clear counter mode */
typedef enum e_pcif_counter_clear_mode
{
    PCIF_PHC_COUNTER_CLEAR_DISABLE = 0U, ///< Disable automatic clear edge count register
    PCIF_PHC_COUNTER_CLEAR_ENABLE  = 1U, ///< Enable automatic clear edge count register
} pcif_phc_counter_clear_mode_t;

/** Incremental mode ABZ phase input */
typedef enum e_pcif_inc_ab_phase_input_mode
{
    PCIF_INC_INPUT_AB_PHASE_PULSE  = 0U, ///< Input mode 0: AB phase pulse
    PCIF_INC_INPUT_A_PHASE_PULSE   = 1U, ///< Input mode 1: A phase pulse (B phase rotation direction)
    PCIF_INC_INPUT_PULSE_SWITCHING = 2U, ///< Input mode 2: Pulse switching
} pcif_inc_ab_input_mode_t;

/** Incremental mode AB phase output */
typedef enum e_pcif_inc_ab_phase_output_mode
{
    PCIF_INC_OUTPUT_SAME_AS_INPUT  = 0U, ///< Output same as input
    PCIF_INC_OUTPUT_AB_PHASE_PULSE = 1U, ///< Output AB phase pulse
} pcif_inc_ab_output_mode_t;

/** Incremental mode Z phase output */
typedef enum e_pcif_inc_z_output_mode
{
    PCIF_INC_Z_OUTPUT_IMMEDIATE  = 0U, ///< Immediate output
    PCIF_INC_Z_OUTPUT_A_SYNC     = 1U, ///< A-phase synchronization
    PCIF_INC_Z_OUTPUT_B_SYNC     = 2U, ///< B-phase synchronization
    PCIF_INC_Z_OUTPUT_PULSE_SYNC = 3U, ///< Pulse synchronization
} pcif_inc_z_output_mode_t;

/** Incremental mode Z phase generate source */
typedef enum e_pcif_inc_z_generate_source
{
    PCIF_INC_Z_PHASE_GEN_NONE     = 0U,        ///< No generation of Z phase
    PCIF_INC_Z_PHASE_GEN_COUNTER  = (1U << 0), ///< Generate Z phase from output/internal counter
    PCIF_INC_Z_PHASE_GEN_INPUT    = (1U << 1), ///< Generate output Z phase from external input signal
    PCIF_INC_Z_PHASE_GEN_CREST    = (1U << 2), ///< Generate output Z phase from crest event signal
    PCIF_INC_Z_PHASE_GEN_TROUGH   = (1U << 3), ///< Generate output Z phase from trough event signal
    PCIF_INC_Z_PHASE_GEN_SOFTWARE = (1U << 4), ///< Generate output Z phase from software trigger
} pcif_inc_z_generate_source_t;

/** Incremental position counter clear enable bit */
typedef enum e_pcif_inc_position_counter_clear
{
    PCIF_INC_COUNTER_CLEAR_NONE     = 0U,        ///< Disable position counter clear
    PCIF_INC_COUNTER_CLEAR_INPUT    = (1U << 1), ///< Clear position counter by Z input signal
    PCIF_INC_COUNTER_CLEAR_CREST    = (1U << 2), ///< Clear position counter by crest event signal
    PCIF_INC_COUNTER_CLEAR_TROUGH   = (1U << 3), ///< Clear position counter by trough event signal
    PCIF_INC_COUNTER_CLEAR_SOFTWARE = (1U << 4), ///< Clear position counter by software trigger
} pcif_inc_position_counter_clear_t;

/** Extended configuration structure for PCIF. */
typedef struct st_pcif_extended_cfg
{
    /** Setting for Phase Counting mode */
    /** Setting Z phase */
    pcif_phc_z_phase_width_t z_width;                                   ///< Set width Z phase
    pcif_phc_z_phase_sync_t  z_sync;                                    ///< Set phase (A/B) to sync Z phase

    /** Carrier Period Setting */
    pcif_phc_carrier_period_mode_t carrier_period_mode;                 ///< Set carrier period mode
    uint16_t carrier_period_diff_threshold;                             ///< Carrier period difference threshold in CCLK_DIV cycles
    uint16_t carrier_period_counts;                                     ///< Carrier period in CCLK_DIV cycles

    /** Edge Counter Setting */
    pcif_phc_counter_clear_mode_t counter_clear_mode;                   ///< Set automatic clear counter mode
    pcif_phc_counter_info_t     * p_init_counter_data;                  ///< Set initial counter data

    /** Error detection enable setting */
    pcif_phc_error_detection_enable_t error_carrier_period_enable;      ///< Set carrier period error detection enable
    pcif_phc_error_detection_enable_t error_edge_count_enable;          ///< Set edge count error detection enable
    pcif_phc_error_detection_enable_t error_edge_count_overflow_enable; ///< Set edge count overflow error detection enable
    pcif_phc_error_detection_enable_t error_old_edge_count_enable;      ///< Set old edge count error detection enable

    /** Setting for Incremental mode */
    uint8_t resolution_ratio_setting;                                   ///< Output resolution: 0 = x1/1, N = x1/(N + 1), max 0x3F

    /** Setting A/B phase */
    pcif_inc_ab_input_mode_t  ab_input_mode;                            ///< Set incremental input mode
    pcif_inc_ab_output_mode_t ab_output_mode;                           ///< Set incremental output mode

    /** Setting Z Phase */
    uint8_t z_output_min_cycles;                                        ///< Minimum cycle Z output: 0 = 1 CCLK_DIV cycle, 0xFF = 256 cycles
    pcif_inc_z_generate_source_t      z_generate_source;                ///< Set Z phase generate source
    pcif_inc_z_output_mode_t          z_output_mode;                    ///< Set incremental Z phase output mode
    pcif_inc_position_counter_clear_t position_clear_source;            ///< Set incremental position counter clear mode
} pcif_extended_cfg_t;

/** Control block used by driver. DO NOT INITIALIZE. Initialization occurs when @ref pcif_api_t::open is called. */
typedef struct st_pcif_instance_ctrl
{
    pcif_cfg_t const        * p_cfg;              // Pointer to the configuration structure
    uint32_t                  open;               // Indicates whether or not the driver is open called
    R_PCIF0_Type            * p_reg;              // Base register for this channel
    pcif_state_t              state;              // PCIF status
    pcif_rotation_direction_t rotation_direction; // Last configured phase counting rotation direction

    /* Pointer to callback and optional working memory */
    /* PCIF will call callback when carrier period occur */
    void (* p_callback)(pcif_callback_args_t *);
    pcif_callback_args_t * p_callback_memory;
    void                 * p_context;  // User defined context passed into callback function
} pcif_instance_ctrl_t;

/**********************************************************************************************************************
 * Exported global variables
 **********************************************************************************************************************/

/** @cond INC_HEADER_DEFS_SEC */
/** Filled in Interface API structure for this Instance. */
extern const pcif_api_t g_pcif_on_pcif;

/** @endcond */

/**********************************************************************************************************************
 * Public Function Prototypes
 **********************************************************************************************************************/
fsp_err_t R_PCIF_Open(pcif_ctrl_t * const p_ctrl, pcif_cfg_t const * const p_cfg);
fsp_err_t R_PCIF_Stop(pcif_ctrl_t * const p_ctrl, pcif_stop_mode_t stop_mode);
fsp_err_t R_PCIF_Start(pcif_ctrl_t * const p_ctrl);
fsp_err_t R_PCIF_SetCounter(pcif_ctrl_t * const                   p_ctrl,
                            pcif_phc_counter_info_t const * const p_counter_data,
                            bool                                  reset_counter);
fsp_err_t R_PCIF_StatusGet(pcif_ctrl_t * const p_ctrl, pcif_status_t * const p_status);
fsp_err_t R_PCIF_SoftwareEventGenerate(pcif_ctrl_t * const p_ctrl);
fsp_err_t R_PCIF_Close(pcif_ctrl_t * const p_ctrl);

/* Common macro for FSP header files. There is also a corresponding FSP_HEADER macro at the top of this file. */
FSP_FOOTER

#endif                                 // R_PCIF_H

/*******************************************************************************************************************//**
 * @} (end defgroup PCIF)
 **********************************************************************************************************************/
